[[section-introduction-and-goals]]
== Introduction and Goals

[role="arc42help"]
****
Describes the relevant requirements and the driving forces that software architects and development team must consider. These include

* underlying business goals, essential features and functional requirements for the system
* quality goals for the architecture
* relevant stakeholders and their expectations
****

Dede es un proyecto que se desarrolla en el curso 21-22 para la asignatura Arquitectura del Software del Grado en Ingeniería del Software de la Universidad de Oviedo.

Dede consiste en una aplicación web de venta de productos alimenticios para animales. El proyecto seguirá la especificación SOLID y uno de sus grandes objetivos es asegurar que cada usuario es propietario de su propia información personal


=== Requirements Overview

[role="arc42help"]
****
.Contents
Short description of the functional requirements, driving forces, extract (or abstract)
of requirements. Link to (hopefully existing) requirements documents
(with version number and information where to find it).

.Motivation
From the point of view of the end users a system is created or modified to
improve support of a business activity and/or improve the quality.

.Form
Short textual description, probably in tabular use-case format.
If requirements documents exist this overview should refer to these documents.

Keep these excerpts as short as possible. Balance readability of this document with potential redundancy w.r.t to requirements documents.
****

La aplicación ofrece un servicio de compra de alimentos para distintas familias de animales, más allá de eso, la aplicación guardará los datos personales del usuario en PODS; de esta manera, la información personal del comprador no la almacenan los propietarios de la aplicación, la almacena el usuario, teniendo así el control sobre ella.

=== Quality Goals

[role="arc42help"]
****
.Contents
The top three (max five) quality goals for the architecture whose fulfillment is of highest importance to the major stakeholders. We really mean quality goals for the architecture. Don't confuse them with project goals. They are not necessarily identical.

.Motivation
You should know the quality goals of your most important stakeholders, since they will influence fundamental architectural decisions. Make sure to be very concrete about these qualities, avoid buzzwords.
If you as an architect do not know how the quality of your work will be judged …

.Form
A table with quality goals and concrete scenarios, ordered by priorities
****

[options="header",cols="1,2"]
|===
|Cualidad|Motivación
| _Privacidad_ | Se persigue que sea el usuario el único propietario de sus datos, para ello el almacenamiento de estos estará descentralizado
| _Seguridad_ | Tanto para proteger al usuario como a la aplicación, esta debe de ser segura y no producir errores ni tener vulnerabilidades que puedan ser atacadas
| _Funcionalidad_ | Con el fin de que la experiencia del usuriario sea positiva, la aplicación no ha tener fallos que interrumpan su uso
| _Accesibilidad_ | Para llegar al mayor público posible, la web debe ser intuitiva y poder ser usada por usuarios no experimentados
|===

=== Stakeholders

[role="arc42help"]
****
.Contents
Explicit overview of stakeholders of the system, i.e. all person, roles or organizations that

* should know the architecture
* have to be convinced of the architecture
* have to work with the architecture or with code
* need the documentation of the architecture for their work
* have to come up with decisions about the system or its development

.Motivation
You should know all parties involved in development of the system or affected by the system.
Otherwise, you may get nasty surprises later in the development process.
These stakeholders determine the extent and the level of detail of your work and its results.

.Form
Table with role names, person names, and their expectations with respect to the architecture and its documentation.
****

[options="header",cols="1,2,2"]
|===
|Role/Name|Contact|Expectations
| _Profesores_ |  | Deberán aportar apoyo al equipo de desarrollo para recibir a cambio una aplicación de la mejor calidad posible
| _Equipo de desarrollo_ | Enol González García
Paula Puerta González | Se espera aprender de una experiencia de trabajo en equipo, dando como resultado nuevos conocimientos de desarrollo, arquitectura, así como un buen dominio de proyectos SOLID
| _Usuarios_ |  | Necesitarán una web amigable, que les facilite el proceso de compra y cumpla con los atributos de calidad establecidos
|===
