[[section-solution-strategy]]
== Solution Strategy

=== Tecnologías
React:: El equipo usará React para la parte gráfica de la aplicación
Solid:: Para que el usuario tenga siempre el control de sus datos se usará Solid con el objetivo de cuidar la privacidad de los usuarios
Docker:: La aplicación se desplegará en Docker

=== Estructura de la aplicación
Patrón MVC:: La aplicación seguirá el patrón Modelo Vista Controlador que separa la lógica de negocio de la presentación y del módulo que gestiona las peticiones

=== Objetivos clave
Privacidad:: Mediante el uso de los pods de Solid queremos que el usuario tenga el control de sus datos lo que sus datos estén menos expuestos lo que lo hace menos vulnerable a sufrir ataques
Calidad del software:: Mediante el uso del patrón MVC y el uso de convenciones de código el equipo quiere hacer que la aplicación sea sencilla de mantener en el futuro además de que sea más fácil de ampliar si así 
lo requiere en el futuro.

=== Decisiones organizativas
Lenguaje de código:: El código será escrito en inglés por cuestiones de mantenibilidad.
Reparto de trabajo:: El equipo ha implementado un tablero Kanban donde mediante issues se repartirán las tareas entre los miembros del equipo
Issues:: Cada miembro del equipo abrirá issues en caso de que se encuentré con un problema. Esto generará un espacio de debate y permitirá resolver las dudas que surgan de manera más sencilla.
Canales de comunicación:: El equipo realizará las reuniones a través de Microsoft Teams además de estar comunicados sus integrantes por la red social Whatsapp. No obstante, la manera oficial 
de expresar nuestras dudas y el reparto de tareas será a través de issues y el tablero Kanban.