[[section-concepts]]
== Cross-cutting Concepts

=== _Conceptos de dominio_
|===
|Concepto | Descripción
|Usuario | Representa al usuario de la tienda. Se obtendrá su información a través de los pods si acepta los permisos necesarios
|===

=== _Seguridad_
La aplicación es segura debido a que el usuario tiene el control sobre los datos que usa la aplicación. Además se controlará el acceso a la aplicación mediante un sistema de roles.

=== _Conceptos de experiencia de usuario_
La aplicación a desarrollar es simple así que el equipo no espera que el usuario tenga dificultades para interactuar con la aplicación. Además el equipo pondrá enfasis
en que la experiencia de usuario sea lo más amigable posible.

=== _Logging_
El usuario se identificará en la aplicación con su usuario y contraseña. Si la identificación es correcta se le redirigirá a la vista correspondiente. En caso contrario
se mostrará un mensaje de error y seguirá en la vista de identificación.

=== _Internacionalización_
La aplicación estará en idioma español aunque el equipo está valorando internacionalizar la aplicación para que esté también disponible en idioma inglés