[[section-design-decisions]]
== Design Decisions


[role="arc42help"]
****
.Contents
Important, expensive, large scale or risky architecture decisions including rationals.
With "decisions" we mean selecting one alternative based on given criteria.

Please use your judgement to decide whether an architectural decision should be documented
here in this central section or whether you better document it locally
(e.g. within the white box template of one building block).

Avoid redundancy. Refer to section 4, where you already captured the most important decisions of your architecture.

.Motivation
Stakeholders of your system should be able to comprehend and retrace your decisions.

.Form
Various options:

* List or table, ordered by importance and consequences or:
* more detailed in form of separate sections per decision
* ADR (architecture decision record) for every important decision
****

=== Role ADMIN

.Motivación
Se necesita un rol administrador para poder cargar productos nuevos de forma fácil.

.Decisión
Es la forma más sencilla de implementar y también de usar una vez que la web esté desplegada. Por ello se decide que el rol admin tenga una vista a la que sólo este pueda acceder.

.Estado
Aceptada

.Consecuencias
Habrá que tener en cuenta detalles de seguridad para que este no sea un agujero de seguridad del sistema.

